@startuml starcraft

scale 1

' 추후 공격받을 객체를 위해 최상위 객체 설정
abstract Object {
    int hp;
}

' SCV가 캐는 광물 자원
class Mineral{}

abstract class Unit extends Object implements Bionic, Mechanic {
    void attack(Object object);
}

abstract class Structure implements Bionic, Mechanic {}

interface Bionic {}

interface Mechanic {}


' -- 테란 --
class Terran implements Unit, Structure {
    
}

class Marin extends Terran {}

class Medic extends Terran {
    @override
    void attack(){};
}

class Tank extends Terran {}

class Vulture extends Terran {}

class Scv extends Terran {
    void collectMineral(Mineral mineral)
}

' -- 저그 --
class Zerg implements Unit{}

class Zergling{}

class Hydra{}

' -- 프로토스 --
class Protoss {}
@enduml