@startuml
title 📱 모바일 타자 연습 애플리케이션 클래스 다이어그램

' 사용자 클래스
class 사용자 {
    - 아이디: String
    - 이름: String
    - 이메일: String
    - 비밀번호: String
}

' 카카오 로그인 클래스
class 카카오로그인 {
    - 카카오로그인(): void
}

' 연습 기록 클래스
class 기록 {
    - 기록아이디: String
    - 정확도: Double
    - 속도: Double
    - 소요시간: Int
    - 연습아이디: String
    - 연습유형: String
    - 연습날짜: Date
    - 시작시간: Date
    - 종료시간: Date
}

' 타자 연습 클래스 (단타/장타 관리)
class 타자연습 {
    - 연습아이디: String
    - 유형: String
    - 제목: String
    - 내용: List<String> 
}


' 클래스 간 관계 정의
사용자 "1" <-- "1" 카카오로그인 : 관리
사용자 "1" <-- "1..*" 기록 : 보유
기록 <-- "0..*" 타자연습 : 생성



@enduml
