name: modu_3_dart_study
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

scripts:
  build: dart run build_runner build --delete-conflicting-outputs
  build-watch: dart run build_runner watch --delete-conflicting-outputs

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  json_annotation: ^4.9.0
  collection: ^1.19.1
  http: ^1.3.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.9.4
  lints: ^5.0.0
  test: ^1.24.0
