@startuml
interface TodoDataSource {
  +getTodos(): Future<List<Todo>>
  +getTodo(id: int): Future<Todo>
}

class TodoDataSourceImpl {
  -_client: http.Client
  +getTodos(): Future<List<Todo>>
  +getTodo(id: int): Future<Todo>
}

class MockTodoDataSource {
  -_client: http.MockClient
  +getTodos(): Future<List<Todo>>
  +getTodo(id: int): Future<Todo>
}

interface TodoRepository {
  +fetchTodos(): Future<List<Todo>>
  +fetchTodoById(id: int): Future<Todo>
}

class TodoRepositoryImpl {
  -dataSource: TodoDataSource
  +fetchTodos(): Future<List<Todo>>
  +fetchTodoById(id: int): Future<Todo>
}

class Todo {
  +userId: int
  +id: int
  +title: String
  +completed: bool
}

TodoDataSourceImpl ..|> TodoDataSource
MockTodoDataSource ..|> TodoDataSource
TodoRepositoryImpl ..|> TodoRepository
TodoRepositoryImpl --> TodoDataSource : 의존
TodoRepositoryImpl --> Todo : 의존
TodoDataSource --> Todo : 의존
@enduml
