@startuml
'https://plantuml.com/class-diagram

enum KeyType {
  padlock(1024)
  button(10_000)
  dial(30_000)
  finger(1_000_000)

  final int max
}

class StrongBox<E> {
  final KeyType keyType
  void put(E data)
  E? get()
}

@enduml