@startuml
abstract class Terran {
}

abstract class Unit extends Terran implements Attackable {

    + String name
    + int healthPoint


}

interface Attackable {
  + void attack(Unit attack)
}

abstract class Structure extends Terran{
}

abstract class Bionic extends Unit {

}

abstract class Mechanic extends Unit {
}

class Marine extends Bionic {

}

class Medic extends Bionic implements Healable {
    + @override void attack(Unit attack)


}

interface Healable {
    + void heal(Bionic unit)
    + void repair(Scv scv)
}

class Tank extends Mechanic {

}

class Vulture extends Mechanic {

}

class Scv extends Mechanic {
    void collect()
    void fixmecha()
}


@enduml