@startuml
'https://plantuml.com/class-diagram
scale 0.7
class Zealot extends BioUnit{
attack()
}
class HighTemplar extends BioUnit {
int MP
magicAttack()
}
class DarkTemplar extends BioUnit{
attack()
}
class Probe extends machineUnit{
int mineralAmount
getMineral()
}
class Dragun extends machineUnit{
attack()
}
abstract class BioUnit extends Unit{
int HP
int useMineral
int Power
medicHeal()
}

abstract class machineUnit extends Unit{
int HP
int useMineral
int Power
}

abstract class Unit implements Protoss{
int barrier

barrierRecover()
makeUnit()
attack()
}

interface Protoss{
barrierRecover()
}

@enduml