@startuml

class Device {}

class Phone {}

class Iphone {}

class Transportation {}

class Car {}

class PorscheTaycan {}

class SearchTool {}

class Dictionary {}

class EnglishDictionary {}

Iphone -|> Phone: 상속
Phone -|> Device : 상속
PorscheTaycan -|> Car : 상속
Car -|> Transportation : 상속
EnglishDictionary -|> Dictionary: 상속
Dictionary -|> SearchTool : 상속

@enduml
