@startuml
interface Comparable {
}

@startuml
class Book implements Comparable<Book> {
  - String title
  - DateTime publishDate
  - String comment
  + Book(title: String, comment: String, year: int, month: int, day: int)
  + copyWith(title: String?, year: int?, month: int?, day: int?, comment: String?): Book
}

Book -|> Comparable : implements

 ' 오버라이드 된 메서드들
Book : + bool operator ==(Object other)
Book : + int get hashCode
Book : + int compareTo(Book other)
@enduml