@startuml
scale 0.7

abstract class Zerg extends StarCraft {
    autoHeal()
}

abstract class ZergUnit extends Zerg {
    int Power
    void attack()
}

abstract class ZergBioUnit extends ZergUnit implements IHealable {}

abstract class ZergStructure extends Zerg {
    ZergUnit makeUnit()
    void makeBuilding()
}

class Zergling extends ZergBioUnit {}

class Hydra extends ZergBioUnit {}

class Drone extends ZergBioUnit {
    int mineralAmount
    getMineral()
}

class Mutal extends ZergBioUnit {}

class Sculzi extends ZergBioUnit {}

interface IHealable {
    void medicHeal(int amount)
}

abstract class StarCraft {
    int HP
    int useMineral
    chooseTribe()
    unitGrouping(int number)
    groupAttack()
    groupMove()
}

@enduml