@startuml

abstract class Asset {
    String name;
    int price;
}

abstract class TangibleAsset extends Asset implements Thing {
    String color;
    double _weight;
}

class Book extends TangibleAsset {
    String isbn;
}

class Computer extends TangibleAsset {
    String makerName;
}

interface Thing {
    double get weight;
    set weight(double value);
}

@enduml