@startuml

interface Thing {
    double get weight;
    set weight(double value);
}

abstract class Asset {}

class TangibleAsset extends Asset implements Thing {
    double _weight;
    String name;
    int price;
    String color;
    {abstract}double get weight
}

class IntangibleAsset extends Asset {

}

class Computer extends TangibleAsset {
    String makerName;
}

class Book extends TangibleAsset {
    String isbn;
}

class Patent extends IntangibleAsset {}


@enduml