@startuml AssetsManagement

abstract class Asset {
    + String name
    + int price
}

interface Thing {
    + double getWeight()
    + void setWeight(double weight)
}

abstract class TangibleAsset extends Asset implements Thing {
    + String color
    - double _weight
    + double get Weight()
    + set Weight(double weight)
}

class Book extends TangibleAsset {
    + String isbn
}

class Computer extends TangibleAsset {
    + String makerName
}

abstract class IntangibleAsset extends Asset {
}

class Patent extends IntangibleAsset{}

@enduml
